# Generated by Django 3.2.18 on 2023-03-23 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField(max_length=2000, null=True)),
                ('is_closed', models.BooleanField()),
                ('url', models.URLField(max_length=2000, null=True)),
                ('review_count', models.IntegerField()),
                ('rating', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price', models.CharField(choices=[('$', 'cheap'), ('$$', 'mild cheap'), ('$$$', 'expensive'), ('$$$$', 'extremely expensive')], max_length=10)),
                ('address1', models.CharField(max_length=200, null=True)),
                ('address2', models.CharField(max_length=200, null=True)),
                ('address3', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(default=None, max_length=200)),
                ('zip_code', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('profile_url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(max_length=2000, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')])),
                ('time_created', models.DateTimeField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewmaster.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewmaster.user')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='users',
            field=models.ManyToManyField(blank=True, through='reviewmaster.Review', to='reviewmaster.User'),
        ),
    ]
