# Generated by Django 3.2.18 on 2023-03-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two Star'), (3, 'Three Star'), (4, 'Four Star'), (5, 'Five Star')])),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewmaster.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewmaster.user')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='users',
            field=models.ManyToManyField(blank=True, through='reviewmaster.Review', to='reviewmaster.User'),
        ),
    ]
