# Generated by Django 3.2.18 on 2023-03-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
